config/routes.rb
Rails.application.routes.draw do
root 'cocktails#index'
  resources :cocktails, only: [ :index, :show, :create, :new, :update ] do
    resources :doses, only: [ :new, :create, :destroy ]

  end
  mount Attachinary::Engine => "/attachinary"
end


#          Prefix Verb   URI Pattern                     Controller#Action
#     restaurants GET    /restaurants(.:format)          restaurants#index
#                 POST   /restaurants(.:format)          restaurants#create
#  new_restaurant GET    /restaurants/new(.:format)      restaurants#new
# edit_restaurant GET    /restaurants/:id/edit(.:format) restaurants#edit
#      restaurant GET    /restaurants/:id(.:format)      restaurants#show
#                 PATCH  /restaurants/:id(.:format)      restaurants#update
#                 DELETE /restaurants/:id(.:format)      restaurants#destroy

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :ingredients, through: :doses
  has_many :doses, dependent: :destroy
  validates :name, presence: :true, uniqueness: true
  has_attachment :photo
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :ingredient
  belongs_to :cocktail
  validates_uniqueness_of :cocktail_id, :scope => [:ingredient_id]
end


# Use scope to validate the uniqueness of a pair of ids.

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  has_many :cocktails
  validates :name, presence: :true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :find_cocktail, only: [:show, :update]

  def index
    @cocktails = Cocktail.all
  end

  def update
    @cocktail.update(cocktail_params)
  end

  def show
    @dose = Dose.new
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render 'new'
    end
  end


  private

  def find_cocktail
    @cocktail = Cocktail.find(params[:id])
  end

  def cocktail_params
  params.require(:cocktail).permit(:name, :id, :photo, :photo_cache)
  end

end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  before_action :set_cocktail, only: [:new, :create, :destroy]
  before_action :set_dose, only: [:destroy]

  def new
    @dose = Dose.new
  end

  def create
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    # @dose.ingredient = @ingredient
    if @dose.save
    redirect_to cocktail_path(@cocktail)
    else
    render :new
    end
  end

  def destroy
    @dose.cocktail = @cocktail
    # @dose.ingredient = @ingredient
    @dose.destroy
    redirect_to cocktail_path(@cocktail)
  end


  private

  def set_cocktail
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def set_dose
    @dose = Dose.find(params[:id])
  end

  # def set_ingredient
  #   @ingredient = Ingredient.find(params[:ingredient_id])
  # end

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/_form.html.erb
<div class = "form-group">
  <%= simple_form_for @cocktail do |f| %>
  <%= f.input :name %>
  <%= f.input :photo, as: :attachinary %>
  <%= f.submit %>
  <% end %>
</div>

app/views/cocktails/create.html.erb
<h1>Cocktails#create</h1>
<p>Find me in app/views/cocktails/create.html.erb</p>

app/views/cocktails/index.html.erb
<div class="container">
  <h1 class="list">My cocktails :</h1>
  <div class="row">
    <% @cocktails.each do |cocktail| %>
    <div class="col-xs-12 col-sm-4">
      <!-- insert <div class="card"> -->
      <!-- <div class="card"> -->
      <% if cocktail.photo? %>
          <% photo_url = cl_image_path cocktail.photo.path, class: 'cocktail-img img-responsive', width: 300, height: 300, crop: :fill %>
        <% else %>
          <% photo_url = image_path('basic_cocktail.jpg') %>

        <% end %>



      <div class= "card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url( '<%= photo_url %>');">
        <div class="card-description">
          <h3>
            <%= cocktail.name %>
          </h3>
          <p><%= link_to "Show details", cocktail_path(cocktail) %></p>
        </div>




      </div>
    </div>
    <% end %>

  </div>
</div>

app/views/cocktails/new.html.erb
<%= render 'form' %>

<%= link_to "Back", cocktails_path, class: "btn btn-primary" %>

app/views/cocktails/show.html.erb
<div class="container">
  <div class="row">

    <div class='col-xs-6 col-xs-offset-3'><h2 class="text-center"><%= @cocktail.name %></h2></div>

    <div class='col-xs-6 col-xs-offset-3 doses-photo'>

    <div class="row">
    <div class='col-xs-6'>
      <h3>Doses:</h3>

      <% @cocktail.doses.each do |dose| %>
        <ul class='description'>
          <li>
            <%= dose.description %> - <%= dose.ingredient.name %><br />
            <%= link_to "Delete a dose",
            cocktail_dose_path(@cocktail, dose), method: :delete %>
          </li>
        </ul>
        <% end %>
        </div>
        <div class='col-xs-6'>
        <div class="cocktail-photo">
          <% if @cocktail.photo? %>
            <%= cl_image_tag @cocktail.photo.path, class:"img-circle", width: 200, height: 200, crop: :fill %>
          <% else %>

            <div class = "form-group">
              <%= simple_form_for @cocktail do |f| %>
                <%= f.input :photo, as: :attachinary %>
                <%= f.submit %>
              <% end %>
            </div>

        </div>
        </div>

      <% end %>

    </div>
    </div>


    <div class='col-xs-6 col-xs-offset-3'>
      <h3 class="text-center">Add a new dose to this cocktail :</h3>
    </div>


    <div class="col-xs-6 col-xs-offset-3">
      <%= render 'doses/form' %>
    </div>





<div class="col-xs-6 col-xs-offset-3">
<%= link_to "Back", cocktails_path, class: "btn btn-primary btn-back" %>
</div>

app/views/doses/_form.html.erb
<div> <%= simple_form_for [@cocktail, @dose] do |f| %>
  <%= f.input :description, placeholder: "Description", wrapper_html: { class: 'form-group' } %>
  <%= f.input :ingredient_id, collection: Ingredient.all, wrapper_html: { class: 'form-group' }%>
  <div class="form-group">
    <%= f.button :submit, class: 'btn btn-block btn-primary' %>
  </div>
  <% end %>
</div>

app/views/doses/create.html.erb
<h1>Doses#create</h1>
<p>Find me in app/views/doses/create.html.erb</p>

app/views/doses/destroy.html.erb
<h1>Doses#destroy</h1>
<p>Find me in app/views/doses/destroy.html.erb</p>

app/views/doses/new.html.erb
<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsMisterCocktail</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= cloudinary_js_config %> <!-- Append this after the main `javascript_include_tag`. -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
</head>

<body>
<%= render 'shared/navbar'  %>


  <%= yield %>
</body>
</html>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "biere.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">


    <!-- Button (call-to-action) -->

<%= link_to t(".top_call_to_action", default: "Add a cocktail"), new_cocktail_path, class: "navbar-wagon-item navbar-wagon-button btn" %>


    <%= link_to t(".top_call_to_action", default: "My cocktails"), cocktails_path, class: "navbar-wagon-item navbar-wagon-button btn" %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>